BloonSounds[blnsnd.dmg] =		{ s : getallassets("HitMoabFast"), v : 0.25, p : 1 };
BloonSounds[blnsnd.dmghard] =	{ s : getallassets("HitMetalSlow"), v : 0.5, p : 1 };
BloonSounds[blnsnd.dmgceram] =	{ s : getallassets("HitCeramic"), v : 0.5, p : 1 };
BloonSounds[blnsnd.dmgamber] =	{ s : getallassets("HitGolden"), v : 0.125, p : 1 };
BloonSounds[blnsnd.dmgmoab] =	{ s : getallassets("HitMoab"), v : 1, p : 1 };
BloonSounds[blnsnd.pop] =		{ s : getallassets("Pop"), v : 0.1, p : 1 };
BloonSounds[blnsnd.popceram] =	{ s : getallassets("CeramicDestroyed"), v : 0.25, p : 1 };
BloonSounds[blnsnd.popaqua] =	{ s : getallassets("PopEffectSplash"), v : 0.25, p : 1 };
BloonSounds[blnsnd.poptough] =	{ s : getallassets("PopStone"), v : 0.25, p : 1 };
BloonSounds[blnsnd.popamber] =	{ s : getallassets("LeadToGold"), v : 0.0625, p : 1 };
BloonSounds[blnsnd.popglass] =	{ s : getallassets("PopGlass"), v : 0.25, p : 1 };
BloonSounds[blnsnd.popmoab0] =	{ s : getallassets("MoabDestroyed"), v : 0.3, p : 2 };
BloonSounds[blnsnd.popmoab1] =	{ s : getallassets("MoabDestroyed"), v : 0.4, p : 1.5 };
BloonSounds[blnsnd.popmoab2] =	{ s : getallassets("MoabDestroyed"), v : 0.5, p : 1 };
BloonSounds[blnsnd.popmoab3] =	{ s : getallassets("ZomgDestroyed"), v : 0.5, p : 1 };
BloonSounds[blnsnd.popmoab4] =	{ s : getallassets("ZomgDestroyed"), v : 0.6, p : 0.8 };
BloonSounds[blnsnd.hitlead] =	{ s : getallassets("HitMetal"), v : 0.25, p : 1 };
BloonSounds[blnsnd.hitaqua] =	{ s : getallassets("WaterJet"), v : 0.5, p : 2 };
BloonSounds[blnsnd.hitcrystal] ={ s : getallassets("HitImmuneGolden"), v : 0.5, p : 0.8 };
BloonSounds[blnsnd.hitfrozen] =	{ s : getallassets("HitIce"), v : 0.25, p : 1 };
BloonSounds[blnsnd.hitzebra] =	{ s : getallassets("HitPurpleSlow"), v : 0.25, p : 1 };
BloonSounds[blnsnd.hitpurple] =	{ s : getallassets("HitPurple"), v : 0.25, p : 1 };
BloonSounds[blnsnd.hitclay] =	{ s : getallassets("HitCeramicCombo"), v : 0.25, p : 1 };
BloonSounds[blnsnd.hittitan] =	{ s : getallassets("HitSteel"), v : 0.125, p : 1 };
BloonSounds[blnsnd.hitkant] =	{ s : getallassets("HitSteelSlow"), v : 0.25, p : 1 };

MusicTracks = [];
array_push(MusicTracks, Main_Theme);
array_push(MusicTracks, Jazz_Theme);
array_push(MusicTracks, Volcano_Theme);
array_push(MusicTracks, Bloons_Rock_Party);
array_push(MusicTracks, Bloons_House_Party);
array_push(MusicTracks, Bloons_Disco_Party);
array_push(MusicTracks, Bloons_Dub_Party__Dub_);
audio_group_load(Music);